### PR TITLE
sniffer: s/CREATE_STACKTEST/THREAD_CREATE_STACKTEST/

### PR DESCRIPTION
**Pull request by haukepetersen**
did not compile, now it does...

### CODE REVIEW

**Comment by authmillenon** [comment]
Would you be so kind to fix this in the microcoap app, too?

**Comment by OlegHahm** [comment]
ACK

**Comment by haukepetersen** [comment]
and go

**Comment by haukepetersen** [comment]
@authmillenon: microcoap seems to have more issues than that, don't really have the time to look into that...

**Pull request merged**
