### PR TITLE
ng_sniffer: use uart0 only for none newlib boards

### PR DESCRIPTION
**Pull request by OlegHahm**
Related and dependent on https://github.com/RIOT-OS/RIOT/pull/3555

### CODE REVIEW

**Comment by OlegHahm** [comment]
Without  RIOT-OS/RIOT#3555 and this PR the sniffer will currently not work on (at least) the Cortex-M platforms.

**Comment by haukepetersen** [comment]
Works for now -> ack and go.

**Comment by OlegHahm** [comment]
Hm, RIOT-OS/RIOT#3555 needs to be merged, too, in order to make this working on all boards.

**Comment by haukepetersen** [comment]
just switched back to this tab and forgot why I put it away earlier...

**Pull request merged**
