### PR TITLE
Provide an application for openwsn

### PR DESCRIPTION
**Pull request by thomaseichinger**

### CODE REVIEW

**Comment by OlegHahm** [comment]
Can you rebase? After that this should be ready to be finally merged.

**Comment by authmillenon** [comment]
> 1. it works only for the two HikoB platforms, where I would expect examples to work on most of the supported platforms

Is this still the case?

**Comment by OlegHahm** [comment]
At least only for at86rf231 based platforms for now. I would like to keep this application here until the plugtest to be more flexible.

Moreover, the concurrency issue while building is still unsolved.

**Comment by thomaseichinger** [comment]
rebased

**Comment by OlegHahm** [comment]
ACK and go

**Pull request merged**
